/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * Factorio Lua API
 */
export interface FactorioApi {
  /**
   * Factorio constants, persistent handles.
   * @{see https://lua-api.factorio.com/latest/defines.html}
   * Factorio does not include types associated with defines :/
   */
  defines: {
    alert_type: {
      entity_destroyed: unknown;
      entity_under_attack: unknown;
      not_enough_construction_robots: unknown;
      no_material_for_construction: unknown;
      not_enough_repair_packs: unknown;
      turret_fire: unknown;
      custom: unknown;
      no_storage: unknown;
      train_out_of_fuel: unknown;
    };
    behavior_result: {
      in_progress: unknown;
      fail: unknown;
      success: unknown;
      deleted: unknown;
    };
    build_check_type: {
      script: unknown;
      manual: unknown;
      manual_ghost: unknown;
      script_ghost: unknown;
      blueprint_ghost: unknown;
      ghost_revive: unknown;
    };
    chain_signal_state: {
      none: unknown;
      all_open: unknown;
      partially_open: unknown;
      none_open: unknown;
    };
    chunk_generated_status: {
      nothing: unknown;
      custom_tiles: unknown;
      basic_tiles: unknown;
      corrected_tiles: unknown;
      tiles: unknown;
      entities: unknown;
    };
    circuit_condition_index: {
      inserter_circuit: unknown;
      inserter_logistic: unknown;
      lamp: unknown;
      arithmetic_combinator: unknown;
      decider_combinator: unknown;
      constant_combinator: unknown;
      offshore_pump: unknown;
      pump: unknown;
    };
    circuit_connector_id: {
      accumulator: unknown;
      constant_combinator: unknown;
      container: unknown;
      programmable_speaker: unknown;
      rail_signal: unknown;
      rail_chain_signal: unknown;
      roboport: unknown;
      storage_tank: unknown;
      wall: unknown;
      electric_pole: unknown;
      inserter: unknown;
      lamp: unknown;
      combinator_input: unknown;
      combinator_output: unknown;
      offshore_pump: unknown;
      pump: unknown;
    };
    command: {
      /**
       * Attack another entity.
       */
      attack: unknown;
      /**
       * Go to a specific position.
       */
      go_to_location: unknown;
      /**
       * Chain commands together, see [defines.compound\_command](https://lua-api.factorio.com/latest/defines.html#defines.compound_command).
       */
      compound: unknown;
      /**
       * Do what your group wants you to do.
       */
      group: unknown;
      /**
       * Go to a place and attack what you see.
       */
      attack_area: unknown;
      /**
       * Chill.
       */
      wander: unknown;
      /**
       * Flee from another entity.
       */
      flee: unknown;
      /**
       * Stop moving and stay where you are.
       */
      stop: unknown;
      /**
       * Go to a position and build a base there.
       */
      build_base: unknown;
    };
    compound_command: {
      /**
       * Fail on first failure. Only succeeds if all commands (executed one after another) succeed.
       */
      logical_and: unknown;
      /**
       * Succeed on first success. Only fails if all commands (executed one after another) fail.
       */
      logical_or: unknown;
      /**
       * Execute all commands in sequence and fail or succeed depending on the return status of the last command.
       */
      return_last: unknown;
    };
    control_behavior: {
      inserter: {
        circuit_mode_of_operation: {
          none: unknown;
          enable_disable: unknown;
          set_filters: unknown;
          read_hand_contents: unknown;
          set_stack_size: unknown;
        };
        hand_read_mode: {
          hold: unknown;
          pulse: unknown;
        };
      };
      logistic_container: {
        circuit_mode_of_operation: {
          send_contents: unknown;
          set_requests: unknown;
        };
      };
      lamp: {
        circuit_mode_of_operation: {
          use_colors: unknown;
        };
      };
      mining_drill: {
        resource_read_mode: {
          this_miner: unknown;
          entire_patch: unknown;
        };
      };
      transport_belt: {
        content_read_mode: {
          pulse: unknown;
          hold: unknown;
        };
      };
      type: {
        /**
         * [LuaContainerControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaContainerControlBehavior.brief)
         */
        container: unknown;
        /**
         * [LuaGenericOnOffControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaGenericOnOffControlBehavior.brief)
         */
        generic_on_off: unknown;
        /**
         * [LuaInserterControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaInserterControlBehavior.brief)
         */
        inserter: unknown;
        /**
         * [LuaLampControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaLampControlBehavior.brief)
         */
        lamp: unknown;
        /**
         * [LuaLogisticContainerControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaLogisticContainerControlBehavior.brief)
         */
        logistic_container: unknown;
        /**
         * [LuaRoboportControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaRoboportControlBehavior.brief)
         */
        roboport: unknown;
        /**
         * [LuaStorageTankControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaStorageTankControlBehavior.brief)
         */
        storage_tank: unknown;
        /**
         * [LuaTrainStopControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaTrainStopControlBehavior.brief)
         */
        train_stop: unknown;
        /**
         * [LuaDeciderCombinatorControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaDeciderCombinatorControlBehavior.brief)
         */
        decider_combinator: unknown;
        /**
         * [LuaArithmeticCombinatorControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaArithmeticCombinatorControlBehavior.brief)
         */
        arithmetic_combinator: unknown;
        /**
         * [LuaConstantCombinatorControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaConstantCombinatorControlBehavior.brief)
         */
        constant_combinator: unknown;
        /**
         * [LuaTransportBeltControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaTransportBeltControlBehavior.brief)
         */
        transport_belt: unknown;
        /**
         * [LuaAccumulatorControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaAccumulatorControlBehavior.brief)
         */
        accumulator: unknown;
        /**
         * [LuaRailSignalControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaRailSignalControlBehavior.brief)
         */
        rail_signal: unknown;
        /**
         * [LuaRailChainSignalControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaRailChainSignalControlBehavior.brief)
         */
        rail_chain_signal: unknown;
        /**
         * [LuaWallControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaWallControlBehavior.brief)
         */
        wall: unknown;
        /**
         * [LuaMiningDrillControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaMiningDrillControlBehavior.brief)
         */
        mining_drill: unknown;
        /**
         * [LuaProgrammableSpeakerControlBehavior](https://lua-api.factorio.com/latest/LuaControlBehavior.html#LuaProgrammableSpeakerControlBehavior.brief)
         */
        programmable_speaker: unknown;
      };
    };
    controllers: {
      /**
       * Can't interact with the world, can only observe. Used in the multiplayer waiting-to-respawn screen.
       */
      ghost: unknown;
      /**
       * The controller controls a character. This is the default controller in freeplay.
       */
      character: unknown;
      /**
       * The controller isn't tied to a character. This is the default controller in sandbox.
       */
      god: unknown;
      /**
       * The Editor Controller near ultimate power to do almost anything in the game.
       */
      editor: unknown;
      /**
       * The player can't interact with the world, and the camera pans around in a predefined manner.
       */
      cutscene: unknown;
      /**
       * Can't change anything in the world but can view anything.
       */
      spectator: unknown;
    };
    deconstruction_item: {
      entity_filter_mode: {
        whitelist: unknown;
        blacklist: unknown;
      };
      tile_filter_mode: {
        whitelist: unknown;
        blacklist: unknown;
      };
      tile_selection_mode: {
        normal: unknown;
        always: unknown;
        never: unknown;
        only: unknown;
      };
    };
    difficulty: {
      easy: unknown;
      normal: unknown;
      hard: unknown;
    };
    difficulty_settings: {
      recipe_difficulty: {
        normal: unknown;
        expensive: unknown;
      };
      technology_difficulty: {
        normal: unknown;
        expensive: unknown;
      };
    };
    direction: {
      north: unknown;
      northeast: unknown;
      east: unknown;
      southeast: unknown;
      south: unknown;
      southwest: unknown;
      west: unknown;
      northwest: unknown;
    };
    disconnect_reason: {
      quit: unknown;
      dropped: unknown;
      reconnect: unknown;
      wrong_input: unknown;
      desync_limit_reached: unknown;
      cannot_keep_up: unknown;
      afk: unknown;
      kicked: unknown;
      kicked_and_deleted: unknown;
      banned: unknown;
      switching_servers: unknown;
    };
    distraction: {
      /**
       * Perform command even if someone attacks the unit.
       */
      none: unknown;
      /**
       * Attack closer enemy entities with force.
       */
      by_enemy: unknown;
      /**
       * Attack closer enemy entities, including entities "built" by player (belts, inserters, chests).
       */
      by_anything: unknown;
      /**
       * Attack when attacked.
       */
      by_damage: unknown;
    };
    entity_status: {
      working: unknown;
      normal: unknown;
      no_power: unknown;
      low_power: unknown;
      no_fuel: unknown;
      disabled_by_control_behavior: unknown;
      disabled_by_script: unknown;
      marked_for_deconstruction: unknown;
      /**
       * Used by power switches.
       */
      networks_connected: unknown;
      /**
       * Used by power switches.
       */
      networks_disconnected: unknown;
      /**
       * Used by accumulators.
       */
      charging: unknown;
      /**
       * Used by accumulators.
       */
      discharging: unknown;
      /**
       * Used by accumulators.
       */
      fully_charged: unknown;
      /**
       * Used by logistic containers.
       */
      out_of_logistic_network: unknown;
      /**
       * Used by assembling machines.
       */
      no_recipe: unknown;
      /**
       * Used by furnaces.
       */
      no_ingredients: unknown;
      /**
       * Used by boilers, fluid turrets and fluid energy sources: Boiler has no fluid to work with.
       */
      no_input_fluid: unknown;
      /**
       * Used by labs.
       */
      no_research_in_progress: unknown;
      /**
       * Used by mining drills.
       */
      no_minable_resources: unknown;
      /**
       * Used by boilers and fluid turrets: Boiler still has some fluid but is about to run out.
       */
      low_input_fluid: unknown;
      /**
       * Used by crafting machines.
       */
      fluid_ingredient_shortage: unknown;
      /**
       * Used by crafting machines, boilers, burner energy sources and reactors: Reactor/burner has full burnt result inventory, boiler has full output fluidbox.
       */
      full_output: unknown;
      /**
       * Used by crafting machines.
       */
      item_ingredient_shortage: unknown;
      /**
       * Used by mining drills when the mining fluid is missing.
       */
      missing_required_fluid: unknown;
      /**
       * Used by labs.
       */
      missing_science_packs: unknown;
      /**
       * Used by inserters.
       */
      waiting_for_source_items: unknown;
      /**
       * Used by inserters and mining drills.
       */
      waiting_for_space_in_destination: unknown;
      /**
       * Used by the rocket silo.
       */
      preparing_rocket_for_launch: unknown;
      /**
       * Used by the rocket silo.
       */
      waiting_to_launch_rocket: unknown;
      /**
       * Used by the rocket silo.
       */
      launching_rocket: unknown;
      /**
       * Used by beacons.
       */
      no_modules_to_transmit: unknown;
      /**
       * Used by roboports.
       */
      recharging_after_power_outage: unknown;
      /**
       * Used by ammo turrets.
       */
      no_ammo: unknown;
      /**
       * Used by heat energy sources.
       */
      low_temperature: unknown;
      /**
       * Used by constant combinators: Combinator is turned off via switch in GUI.
       */
      disabled: unknown;
      /**
       * Used by lamps.
       */
      turned_off_during_daytime: unknown;
      /**
       * Used by rail signals.
       */
      not_connected_to_rail: unknown;
      /**
       * Used by rail signals.
       */
      cant_divide_segments: unknown;
    };
    events: {
      on_tick: unknown;
      on_gui_click: unknown;
      on_gui_confirmed: unknown;
      on_gui_text_changed: unknown;
      on_gui_checked_state_changed: unknown;
      on_entity_died: unknown;
      on_post_entity_died: unknown;
      on_entity_damaged: unknown;
      on_picked_up_item: unknown;
      on_built_entity: unknown;
      on_sector_scanned: unknown;
      on_player_mined_item: unknown;
      on_pre_build: unknown;
      on_rocket_launched: unknown;
      on_pre_player_mined_item: unknown;
      on_chunk_generated: unknown;
      on_player_crafted_item: unknown;
      on_robot_built_entity: unknown;
      on_robot_pre_mined: unknown;
      on_robot_mined: unknown;
      on_research_started: unknown;
      on_research_finished: unknown;
      on_player_rotated_entity: unknown;
      on_marked_for_deconstruction: unknown;
      on_cancelled_deconstruction: unknown;
      on_trigger_created_entity: unknown;
      on_trigger_fired_artillery: unknown;
      on_train_changed_state: unknown;
      on_player_created: unknown;
      on_resource_depleted: unknown;
      on_player_driving_changed_state: unknown;
      on_force_created: unknown;
      on_forces_merging: unknown;
      on_player_cursor_stack_changed: unknown;
      on_pre_entity_settings_pasted: unknown;
      on_entity_settings_pasted: unknown;
      on_player_main_inventory_changed: unknown;
      on_player_armor_inventory_changed: unknown;
      on_player_ammo_inventory_changed: unknown;
      on_player_gun_inventory_changed: unknown;
      on_player_placed_equipment: unknown;
      on_player_removed_equipment: unknown;
      on_pre_player_died: unknown;
      on_player_died: unknown;
      on_player_respawned: unknown;
      on_player_joined_game: unknown;
      on_player_left_game: unknown;
      on_player_built_tile: unknown;
      on_player_mined_tile: unknown;
      on_robot_built_tile: unknown;
      on_robot_mined_tile: unknown;
      on_player_selected_area: unknown;
      on_player_alt_selected_area: unknown;
      on_player_changed_surface: unknown;
      on_selected_entity_changed: unknown;
      on_market_item_purchased: unknown;
      on_player_dropped_item: unknown;
      on_biter_base_built: unknown;
      on_player_changed_force: unknown;
      on_entity_renamed: unknown;
      on_gui_selection_state_changed: unknown;
      on_runtime_mod_setting_changed: unknown;
      on_difficulty_settings_changed: unknown;
      on_surface_created: unknown;
      on_surface_deleted: unknown;
      on_pre_surface_deleted: unknown;
      on_player_mined_entity: unknown;
      on_robot_mined_entity: unknown;
      on_train_created: unknown;
      on_gui_elem_changed: unknown;
      on_player_setup_blueprint: unknown;
      on_player_deconstructed_area: unknown;
      on_player_configured_blueprint: unknown;
      on_console_chat: unknown;
      on_console_command: unknown;
      on_player_removed: unknown;
      on_pre_player_removed: unknown;
      on_player_used_capsule: unknown;
      script_raised_built: unknown;
      script_raised_destroy: unknown;
      script_raised_revive: unknown;
      script_raised_set_tiles: unknown;
      on_player_promoted: unknown;
      on_player_demoted: unknown;
      on_combat_robot_expired: unknown;
      on_player_changed_position: unknown;
      on_mod_item_opened: unknown;
      on_gui_opened: unknown;
      on_gui_closed: unknown;
      on_gui_value_changed: unknown;
      on_player_muted: unknown;
      on_player_unmuted: unknown;
      on_player_cheat_mode_enabled: unknown;
      on_player_cheat_mode_disabled: unknown;
      on_character_corpse_expired: unknown;
      on_pre_ghost_deconstructed: unknown;
      on_player_pipette: unknown;
      on_player_display_resolution_changed: unknown;
      on_player_display_scale_changed: unknown;
      on_pre_player_crafted_item: unknown;
      on_player_cancelled_crafting: unknown;
      on_chunk_charted: unknown;
      on_technology_effects_reset: unknown;
      on_force_reset: unknown;
      on_land_mine_armed: unknown;
      on_forces_merged: unknown;
      on_player_trash_inventory_changed: unknown;
      on_pre_player_left_game: unknown;
      on_pre_surface_cleared: unknown;
      on_surface_cleared: unknown;
      on_chunk_deleted: unknown;
      on_pre_chunk_deleted: unknown;
      on_train_schedule_changed: unknown;
      on_player_banned: unknown;
      on_player_kicked: unknown;
      on_player_unbanned: unknown;
      on_rocket_launch_ordered: unknown;
      on_script_path_request_finished: unknown;
      on_ai_command_completed: unknown;
      on_marked_for_upgrade: unknown;
      on_cancelled_upgrade: unknown;
      on_player_toggled_map_editor: unknown;
      on_entity_cloned: unknown;
      on_area_cloned: unknown;
      on_brush_cloned: unknown;
      on_game_created_from_scenario: unknown;
      on_surface_imported: unknown;
      on_surface_renamed: unknown;
      on_player_toggled_alt_mode: unknown;
      on_player_repaired_entity: unknown;
      on_player_fast_transferred: unknown;
      on_pre_robot_exploded_cliff: unknown;
      on_robot_exploded_cliff: unknown;
      on_entity_spawned: unknown;
      on_cutscene_waypoint_reached: unknown;
      on_unit_group_created: unknown;
      on_unit_added_to_group: unknown;
      on_unit_removed_from_group: unknown;
      on_unit_group_finished_gathering: unknown;
      on_build_base_arrived: unknown;
      on_chart_tag_added: unknown;
      on_chart_tag_modified: unknown;
      on_chart_tag_removed: unknown;
      on_lua_shortcut: unknown;
      on_gui_location_changed: unknown;
      on_gui_selected_tab_changed: unknown;
      on_gui_switch_state_changed: unknown;
      on_force_cease_fire_changed: unknown;
      on_force_friends_changed: unknown;
      on_string_translated: unknown;
      on_script_trigger_effect: unknown;
      on_player_set_quick_bar_slot: unknown;
      on_pre_player_toggled_map_editor: unknown;
      on_pre_script_inventory_resized: unknown;
      on_script_inventory_resized: unknown;
      on_entity_destroyed: unknown;
      on_player_clicked_gps_tag: unknown;
      on_player_flushed_fluid: unknown;
      on_permission_group_edited: unknown;
      on_pre_permission_string_imported: unknown;
      on_permission_string_imported: unknown;
      on_pre_permission_group_deleted: unknown;
      on_permission_group_deleted: unknown;
      on_permission_group_added: unknown;
      on_cutscene_cancelled: unknown;
      on_player_configured_spider_remote: unknown;
      on_player_used_spider_remote: unknown;
      on_spider_command_completed: unknown;
    };
    flow_precision_index: {
      one_second: unknown;
      one_minute: unknown;
      ten_minutes: unknown;
      one_hour: unknown;
      ten_hours: unknown;
      fifty_hours: unknown;
      two_hundred_fifty_hours: unknown;
      one_thousand_hours: unknown;
    };
    group_state: {
      gathering: unknown;
      moving: unknown;
      attacking_distraction: unknown;
      attacking_target: unknown;
      finished: unknown;
      pathfinding: unknown;
      wander_in_group: unknown;
    };
    gui_type: {
      none: unknown;
      entity: unknown;
      research: unknown;
      controller: unknown;
      production: unknown;
      item: unknown;
      bonus: unknown;
      trains: unknown;
      achievement: unknown;
      blueprint_library: unknown;
      equipment: unknown;
      logistic: unknown;
      other_player: unknown;
      permissions: unknown;
      tutorials: unknown;
      custom: unknown;
      server_management: unknown;
      player_management: unknown;
      tile: unknown;
    };
    input_action: {
      activate_copy: unknown;
      activate_cut: unknown;
      activate_paste: unknown;
      add_permission_group: unknown;
      add_train_station: unknown;
      admin_action: unknown;
      alt_select_area: unknown;
      alt_select_blueprint_entities: unknown;
      alternative_copy: unknown;
      begin_mining: unknown;
      begin_mining_terrain: unknown;
      build: unknown;
      build_rail: unknown;
      build_terrain: unknown;
      cancel_craft: unknown;
      cancel_deconstruct: unknown;
      cancel_new_blueprint: unknown;
      cancel_research: unknown;
      cancel_upgrade: unknown;
      change_active_character_tab: unknown;
      change_active_item_group_for_crafting: unknown;
      change_active_item_group_for_filters: unknown;
      change_active_quick_bar: unknown;
      change_arithmetic_combinator_parameters: unknown;
      change_decider_combinator_parameters: unknown;
      change_entity_label: unknown;
      change_item_description: unknown;
      change_item_label: unknown;
      change_multiplayer_config: unknown;
      change_picking_state: unknown;
      change_programmable_speaker_alert_parameters: unknown;
      change_programmable_speaker_circuit_parameters: unknown;
      change_programmable_speaker_parameters: unknown;
      change_riding_state: unknown;
      change_shooting_state: unknown;
      change_train_stop_station: unknown;
      change_train_wait_condition: unknown;
      change_train_wait_condition_data: unknown;
      check_c_r_c: unknown;
      check_c_r_c_heuristic: unknown;
      clear_cursor: unknown;
      connect_rolling_stock: unknown;
      copy: unknown;
      copy_entity_settings: unknown;
      copy_opened_blueprint: unknown;
      copy_opened_item: unknown;
      craft: unknown;
      cursor_split: unknown;
      cursor_transfer: unknown;
      custom_input: unknown;
      cycle_blueprint_book_backwards: unknown;
      cycle_blueprint_book_forwards: unknown;
      deconstruct: unknown;
      delete_blueprint_library: unknown;
      delete_blueprint_record: unknown;
      delete_custom_tag: unknown;
      delete_permission_group: unknown;
      destroy_item: unknown;
      destroy_opened_item: unknown;
      disconnect_all_players: unknown;
      disconnect_rolling_stock: unknown;
      drag_train_schedule: unknown;
      drag_train_wait_condition: unknown;
      drop_blueprint_record: unknown;
      drop_item: unknown;
      edit_blueprint_tool_preview: unknown;
      edit_custom_tag: unknown;
      edit_permission_group: unknown;
      export_blueprint: unknown;
      fast_entity_split: unknown;
      fast_entity_transfer: unknown;
      flush_opened_entity_fluid: unknown;
      flush_opened_entity_specific_fluid: unknown;
      game_created_from_scenario: unknown;
      go_to_train_station: unknown;
      grab_blueprint_record: unknown;
      gui_checked_state_changed: unknown;
      gui_click: unknown;
      gui_confirmed: unknown;
      gui_elem_changed: unknown;
      gui_location_changed: unknown;
      gui_selected_tab_changed: unknown;
      gui_selection_state_changed: unknown;
      gui_switch_state_changed: unknown;
      gui_text_changed: unknown;
      gui_value_changed: unknown;
      import_blueprint: unknown;
      import_blueprint_string: unknown;
      import_blueprints_filtered: unknown;
      import_permissions_string: unknown;
      inventory_split: unknown;
      inventory_transfer: unknown;
      launch_rocket: unknown;
      lua_shortcut: unknown;
      map_editor_action: unknown;
      market_offer: unknown;
      mod_settings_changed: unknown;
      multiplayer_init: unknown;
      open_achievements_gui: unknown;
      open_blueprint_library_gui: unknown;
      open_blueprint_record: unknown;
      open_bonus_gui: unknown;
      open_character_gui: unknown;
      open_current_vehicle_gui: unknown;
      open_equipment: unknown;
      open_gui: unknown;
      open_item: unknown;
      open_logistic_gui: unknown;
      open_mod_item: unknown;
      open_parent_of_opened_item: unknown;
      open_production_gui: unknown;
      open_technology_gui: unknown;
      open_tips_and_tricks_gui: unknown;
      open_train_gui: unknown;
      open_train_station_gui: unknown;
      open_trains_gui: unknown;
      paste_entity_settings: unknown;
      place_equipment: unknown;
      player_admin_change: unknown;
      player_join_game: unknown;
      quick_bar_pick_slot: unknown;
      quick_bar_set_selected_page: unknown;
      quick_bar_set_slot: unknown;
      reassign_blueprint: unknown;
      reload_script: unknown;
      reload_script_data_too_large: unknown;
      remove_cables: unknown;
      remove_train_station: unknown;
      reset_assembling_machine: unknown;
      reset_item: unknown;
      rotate_entity: unknown;
      select_area: unknown;
      select_blueprint_entities: unknown;
      select_entity_slot: unknown;
      select_item: unknown;
      select_mapper_slot: unknown;
      select_next_valid_gun: unknown;
      select_tile_slot: unknown;
      send_spidertron: unknown;
      server_command: unknown;
      set_allow_commands: unknown;
      set_auto_launch_rocket: unknown;
      set_autosort_inventory: unknown;
      set_behavior_mode: unknown;
      set_car_weapons_control: unknown;
      set_circuit_condition: unknown;
      set_circuit_mode_of_operation: unknown;
      set_controller_logistic_trash_filter_item: unknown;
      set_deconstruction_item_tile_selection_mode: unknown;
      set_deconstruction_item_trees_and_rocks_only: unknown;
      set_entity_color: unknown;
      set_entity_energy_property: unknown;
      set_entity_logistic_trash_filter_item: unknown;
      set_filter: unknown;
      set_flat_controller_gui: unknown;
      set_heat_interface_mode: unknown;
      set_heat_interface_temperature: unknown;
      set_infinity_container_filter_item: unknown;
      set_infinity_container_remove_unfiltered_items: unknown;
      set_infinity_pipe_filter: unknown;
      set_inserter_max_stack_size: unknown;
      set_inventory_bar: unknown;
      set_linked_container_link_i_d: unknown;
      set_logistic_filter_item: unknown;
      set_logistic_filter_signal: unknown;
      set_player_color: unknown;
      set_recipe_notifications: unknown;
      set_request_from_buffers: unknown;
      set_research_finished_stops_game: unknown;
      set_signal: unknown;
      set_splitter_priority: unknown;
      set_train_stopped: unknown;
      set_trains_limit: unknown;
      set_vehicle_automatic_targeting_parameters: unknown;
      setup_assembling_machine: unknown;
      setup_blueprint: unknown;
      setup_single_blueprint_record: unknown;
      singleplayer_init: unknown;
      smart_pipette: unknown;
      spawn_item: unknown;
      stack_split: unknown;
      stack_transfer: unknown;
      start_repair: unknown;
      start_research: unknown;
      start_walking: unknown;
      stop_building_by_moving: unknown;
      switch_connect_to_logistic_network: unknown;
      switch_constant_combinator_state: unknown;
      switch_inserter_filter_mode_state: unknown;
      switch_power_switch_state: unknown;
      switch_to_rename_stop_gui: unknown;
      take_equipment: unknown;
      toggle_deconstruction_item_entity_filter_mode: unknown;
      toggle_deconstruction_item_tile_filter_mode: unknown;
      toggle_driving: unknown;
      toggle_enable_vehicle_logistics_while_moving: unknown;
      toggle_entity_logistic_requests: unknown;
      toggle_equipment_movement_bonus: unknown;
      toggle_map_editor: unknown;
      toggle_personal_logistic_requests: unknown;
      toggle_personal_roboport: unknown;
      toggle_show_entity_info: unknown;
      translate_string: unknown;
      undo: unknown;
      upgrade: unknown;
      upgrade_opened_blueprint_by_item: unknown;
      upgrade_opened_blueprint_by_record: unknown;
      use_artillery_remote: unknown;
      use_item: unknown;
      wire_dragging: unknown;
      write_to_console: unknown;
    };
    inventory: {
      fuel: unknown;
      burnt_result: unknown;
      chest: unknown;
      furnace_source: unknown;
      furnace_result: unknown;
      furnace_modules: unknown;
      character_main: unknown;
      character_guns: unknown;
      character_ammo: unknown;
      character_armor: unknown;
      character_vehicle: unknown;
      character_trash: unknown;
      god_main: unknown;
      editor_main: unknown;
      editor_guns: unknown;
      editor_ammo: unknown;
      editor_armor: unknown;
      roboport_robot: unknown;
      roboport_material: unknown;
      robot_cargo: unknown;
      robot_repair: unknown;
      assembling_machine_input: unknown;
      assembling_machine_output: unknown;
      assembling_machine_modules: unknown;
      lab_input: unknown;
      lab_modules: unknown;
      mining_drill_modules: unknown;
      item_main: unknown;
      rocket_silo_rocket: unknown;
      rocket_silo_result: unknown;
      rocket: unknown;
      car_trunk: unknown;
      car_ammo: unknown;
      cargo_wagon: unknown;
      turret_ammo: unknown;
      beacon_modules: unknown;
      character_corpse: unknown;
      artillery_turret_ammo: unknown;
      artillery_wagon_ammo: unknown;
      spider_trunk: unknown;
      spider_ammo: unknown;
      spider_trash: unknown;
    };
    logistic_member_index: {
      logistic_container: unknown;
      vehicle_storage: unknown;
      character_requester: unknown;
      character_storage: unknown;
      character_provider: unknown;
      generic_on_off_behavior: unknown;
    };
    logistic_mode: {
      none: unknown;
      active_provider: unknown;
      storage: unknown;
      requester: unknown;
      passive_provider: unknown;
      buffer: unknown;
    };
    mouse_button_type: {
      none: unknown;
      left: unknown;
      right: unknown;
      middle: unknown;
    };
    rail_connection_direction: {
      left: unknown;
      straight: unknown;
      right: unknown;
      none: unknown;
    };
    rail_direction: {
      front: unknown;
      back: unknown;
    };
    relative_gui_position: {
      top: unknown;
      bottom: unknown;
      left: unknown;
      right: unknown;
    };
    relative_gui_type: {
      accumulator_gui: unknown;
      achievement_gui: unknown;
      additional_entity_info_gui: unknown;
      admin_gui: unknown;
      arithmetic_combinator_gui: unknown;
      armor_gui: unknown;
      assembling_machine_gui: unknown;
      assembling_machine_select_recipe_gui: unknown;
      beacon_gui: unknown;
      blueprint_book_gui: unknown;
      blueprint_library_gui: unknown;
      blueprint_setup_gui: unknown;
      bonus_gui: unknown;
      burner_equipment_gui: unknown;
      car_gui: unknown;
      constant_combinator_gui: unknown;
      container_gui: unknown;
      controller_gui: unknown;
      decider_combinator_gui: unknown;
      deconstruction_item_gui: unknown;
      electric_energy_interface_gui: unknown;
      electric_network_gui: unknown;
      entity_variations_gui: unknown;
      entity_with_energy_source_gui: unknown;
      equipment_grid_gui: unknown;
      furnace_gui: unknown;
      generic_on_off_entity_gui: unknown;
      heat_interface_gui: unknown;
      infinity_pipe_gui: unknown;
      inserter_gui: unknown;
      item_with_inventory_gui: unknown;
      lab_gui: unknown;
      lamp_gui: unknown;
      linked_container_gui: unknown;
      loader_gui: unknown;
      logistic_gui: unknown;
      market_gui: unknown;
      mining_drill_gui: unknown;
      other_player_gui: unknown;
      permissions_gui: unknown;
      pipe_gui: unknown;
      power_switch_gui: unknown;
      production_gui: unknown;
      programmable_speaker_gui: unknown;
      rail_chain_signal_gui: unknown;
      rail_signal_gui: unknown;
      reactor_gui: unknown;
      rename_stop_gui: unknown;
      resource_entity_gui: unknown;
      roboport_gui: unknown;
      rocket_silo_gui: unknown;
      server_config_gui: unknown;
      spider_vehicle_gui: unknown;
      splitter_gui: unknown;
      standalone_character_gui: unknown;
      storage_tank_gui: unknown;
      tile_variations_gui: unknown;
      train_gui: unknown;
      train_stop_gui: unknown;
      trains_gui: unknown;
      transport_belt_gui: unknown;
      upgrade_item_gui: unknown;
      wall_gui: unknown;
    };
    render_mode: {
      game: unknown;
      chart: unknown;
      chart_zoomed_in: unknown;
    };
    rich_text_setting: {
      enabled: unknown;
      disabled: unknown;
      highlight: unknown;
    };
    riding: {
      acceleration: {
        nothing: unknown;
        accelerating: unknown;
        braking: unknown;
        reversing: unknown;
      };
      direction: {
        left: unknown;
        straight: unknown;
        right: unknown;
      };
    };
    shooting: {
      not_shooting: unknown;
      shooting_enemies: unknown;
      shooting_selected: unknown;
    };
    signal_state: {
      /**
       * Green.
       */
      open: unknown;
      /**
       * Red.
       */
      closed: unknown;
      /**
       * Orange.
       */
      reserved: unknown;
      /**
       * Red - From circuit network.
       */
      reserved_by_circuit_network: unknown;
    };
    train_state: {
      /**
       * Normal state -- following the path.
       */
      on_the_path: unknown;
      /**
       * Had path and lost it -- must stop.
       */
      path_lost: unknown;
      /**
       * Doesn't have anywhere to go.
       */
      no_schedule: unknown;
      /**
       * Has no path and is stopped.
       */
      no_path: unknown;
      /**
       * Braking before a rail signal.
       */
      arrive_signal: unknown;
      /**
       * Waiting at a signal.
       */
      wait_signal: unknown;
      /**
       * Braking before a station.
       */
      arrive_station: unknown;
      /**
       * Waiting at a station.
       */
      wait_station: unknown;
      /**
       * Switched to manual control and has to stop.
       */
      manual_control_stop: unknown;
      /**
       * Can move if user explicitly sits in and rides the train.
       */
      manual_control: unknown;
    };
    transport_line: {
      left_line: unknown;
      right_line: unknown;
      left_underground_line: unknown;
      right_underground_line: unknown;
      secondary_left_line: unknown;
      secondary_right_line: unknown;
      left_split_line: unknown;
      right_split_line: unknown;
      secondary_left_split_line: unknown;
      secondary_right_split_line: unknown;
    };
    wire_connection_id: {
      electric_pole: unknown;
      power_switch_left: unknown;
      power_switch_right: unknown;
    };
    wire_type: {
      red: unknown;
      green: unknown;
      copper: unknown;
    };
  };
}
